import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* App Header */}
        <header style={{
          width: "100%",
          background: "#fff",
          borderBottom: "1px solid #eee",
          padding: "0 32px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          minHeight: 72,
          position: "sticky",
          top: 0,
          zIndex: 100,
        }}>
          {/* Logo */}
          <a href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
            <Image src="/globe.svg" alt="CoachFinder Logo" width={36} height={36} style={{ marginRight: 4 }} />
            <span style={{ fontWeight: 700, fontSize: 22, color: "#1a1a1a", letterSpacing: -1 }}>CoachFinder FEB</span>
          </a>
          {/* Main Nav */}
          <nav style={{ display: "flex", gap: 32, alignItems: "center" }}>
            <a href="/directorio" style={{ color: "#222", fontWeight: 500, textDecoration: "none" }}>Directorio de entrenadores</a>
            <a href="#faqs" style={{ color: "#222", fontWeight: 500, textDecoration: "none" }}>FAQs</a>
            <a href="#noticias" style={{ color: "#222", fontWeight: 500, textDecoration: "none" }}>Noticias</a>
            <a href="#precios" style={{ color: "#222", fontWeight: 500, textDecoration: "none" }}>Pricing</a>
          </nav>
          {/* CTAs */}
          <div style={{ display: "flex", gap: 12 }}>
            <a href="#acceso-entrenadores" className="button secondary" style={{ minWidth: 140 }}>Log In</a>
            <a href="#acceso-clubes" className="button" style={{ minWidth: 140 }}>Darme de alta</a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
